# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(637, 514)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 10, 633, 491))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 4, 1, 1)
        self.kobieta = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        self.kobieta.setObjectName("kobieta")
        self.gridLayout.addWidget(self.kobieta, 4, 1, 1, 1)
        self.meszczyzna = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        self.meszczyzna.setObjectName("meszczyzna")
        self.gridLayout.addWidget(self.meszczyzna, 4, 3, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(parent=self.gridLayoutWidget)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 3, 0, 1, 5)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 85, 0);")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
"color: rgb(0, 85, 0);")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.nazwa = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.nazwa.setObjectName("nazwa")
        self.gridLayout.addWidget(self.nazwa, 0, 3, 1, 1)
        self.wynik = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.wynik.setText("")
        self.wynik.setObjectName("wynik")
        self.gridLayout.addWidget(self.wynik, 2, 2, 1, 3)
        self.line = QtWidgets.QFrame(parent=self.gridLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 6, 0, 1, 2)
        self.kalorie = QtWidgets.QSpinBox(parent=self.gridLayoutWidget)
        self.kalorie.setEnabled(True)
        self.kalorie.setMinimumSize(QtCore.QSize(200, 0))
        self.kalorie.setMaximum(1000000000)
        self.kalorie.setDisplayIntegerBase(10)
        self.kalorie.setObjectName("kalorie")
        self.gridLayout.addWidget(self.kalorie, 0, 1, 1, 1)
        self.mala = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        self.mala.setObjectName("mala")
        self.gridLayout.addWidget(self.mala, 5, 0, 1, 2)
        self.srednia = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        self.srednia.setObjectName("srednia")
        self.gridLayout.addWidget(self.srednia, 5, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(49, 223, 36);")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 2)
        self.duza = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        self.duza.setObjectName("duza")
        self.gridLayout.addWidget(self.duza, 5, 3, 1, 2)
        self.lista = QtWidgets.QListWidget(parent=self.gridLayoutWidget)
        self.lista.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.lista.setProperty("showDropIndicator", False)
        self.lista.setObjectName("lista")
        self.gridLayout.addWidget(self.lista, 1, 0, 1, 5)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Dodaj"))
        self.kobieta.setText(_translate("Dialog", "kobieta"))
        self.meszczyzna.setText(_translate("Dialog", "mężczyzna"))
        self.label_2.setText(_translate("Dialog", "Nazwa Posiłku"))
        self.label.setText(_translate("Dialog", "Kalorie"))
        self.mala.setText(_translate("Dialog", "mała aktywność fizyczna"))
        self.srednia.setText(_translate("Dialog", "średnia aktywność fizyczna"))
        self.label_3.setText(_translate("Dialog", "suma spożytych kalorii."))
        self.duza.setText(_translate("Dialog", "duża aktywność fizyczna"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
